"""
Generates validation_report.md — the human-readable summary of everything
the other validation modules computed. Pulls only from the values it's
given (never re-derives numbers), so the report always matches the CSVs.
"""

from pathlib import Path
from typing import Dict, Optional

import pandas as pd

# Pass/fail thresholds. These are deliberately simple and stated up front
# (per the roadmap: "define validation criteria before looking at
# results"). Adjust here if your methodology calls for different
# tolerances — the report always shows the threshold used.
FREQUENCY_ERROR_TOLERANCE_HZ = 0.5
CLEAN_PRESERVATION_TOLERANCE = 0   # violations allowed
EVENT_PRESERVATION_TOLERANCE = 0   # violations allowed


def _pass_fail(condition: bool) -> str:
    return "**PASS**" if condition else "**FAIL**"


def generate_report(outdir: str, dataset_summary: Dict, signal_summary: Dict,
                     spatial_df: pd.DataFrame, robustpdx_df: Optional[pd.DataFrame],
                     comparison_df: pd.DataFrame, cfg) -> str:
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    freq_pass = signal_summary.get("mean_frequency_error_hz", float("nan")) <= FREQUENCY_ERROR_TOLERANCE_HZ
    clean_pass = signal_summary.get("clean_preservation_violations", 1) <= CLEAN_PRESERVATION_TOLERANCE
    event_pass = signal_summary.get("event_preservation_violations", 1) <= EVENT_PRESERVATION_TOLERANCE
    amp_corr = signal_summary.get("amplitude_rms_correlation", float("nan"))
    amp_pass = (amp_corr == amp_corr) and amp_corr > 0.3  # loosely "positive relationship"

    robustpdx_available = robustpdx_df is not None and not robustpdx_df.empty

    lines = []
    lines.append("# TREMORSHIELD — Synthetic Tremor Validation Report\n")

    lines.append("## 1. Objective\n")
    lines.append(
        "Validate whether the synthetic tremor generated by the injection "
        "stage (`src/tremor_model.py`, `src/injection.py`) actually "
        "possesses the mathematical, spectral, amplitude, and spatial "
        "properties it was designed to have — before this data is used to "
        "train a Random Forest classifier or evaluate an Adaptive Kalman "
        "Filter.\n"
    )

    lines.append("## 2. Dataset summary\n")
    for k, v in dataset_summary.items():
        lines.append(f"- **{k}**: {v}")
    lines.append("")

    lines.append("## 3. Tremor model being validated\n")
    lines.append(
        "T(t) = A · r(t) · sin(2π f t + φ), applied transverse to the "
        "instantaneous direction of travel, f ∈ {4, 6, 8, 10} Hz, "
        f"A ∈ {list(cfg.amplitudes_px)} px, r(t) an Ornstein–Uhlenbeck-style "
        "stochastic envelope. Adapted from Kulkarni, Accoto & Campolo "
        "(2024); see `src/tremor_model.py` for the full derivation and "
        "citations (Rocon et al., 2004; Randall, 1973; Gantert et al., "
        "1992). The pixel amplitudes A are engineering simulation "
        "parameters and are **not** claimed to be physiologically "
        "equivalent to the 13 rad/s² wrist angular acceleration reported "
        "in the source literature.\n"
    )

    lines.append("## 4. Mathematical validation\n")
    lines.append(f"- Trials evaluated: {signal_summary.get('n_tremor_trials_evaluated')}")
    lines.append(f"- Trials skipped for frequency analysis (insufficient samples): "
                  f"{signal_summary.get('n_trials_skipped_for_frequency')}")
    lines.append("")

    lines.append("## 5. Frequency validation\n")
    lines.append(f"- Mean absolute frequency error: "
                  f"{signal_summary.get('mean_frequency_error_hz'):.3f} Hz "
                  f"({signal_summary.get('mean_frequency_error_percent'):.1f}%)")
    lines.append(f"- Tolerance: ≤ {FREQUENCY_ERROR_TOLERANCE_HZ} Hz")
    lines.append(f"- Result: {_pass_fail(freq_pass)}")
    lines.append("- See `frequency_validation.csv`, "
                  "`validation_plots/psd_by_frequency.png`, "
                  "`validation_plots/detected_vs_injected_freq.png`.\n")

    lines.append("## 6. Amplitude validation\n")
    lines.append(
        "The configured amplitude A is the pre-multiplication scale in "
        "T(t) = A·r(t)·sin(...), with 0 < r(t) ≤ 1 — RMS residual is "
        "expected to be well below A, never equal to it. What matters is "
        "whether RMS residual increases monotonically with A."
    )
    lines.append(f"- Correlation(configured amplitude, RMS residual): "
                  f"{amp_corr:.3f}" if amp_corr == amp_corr else "- Correlation: n/a")
    lines.append(f"- Result: {_pass_fail(amp_pass)} (positive relationship expected)")
    lines.append("- See `amplitude_validation.csv`, "
                  "`validation_plots/amplitude_vs_rms.png`.\n")

    lines.append("## 7. Stochastic-envelope validation\n")
    lines.append(
        "r(t) itself is not persisted in the output CSVs, so this is a "
        "Hilbert-envelope PROXY estimate of A·r(t), accurate only where "
        "r(t) varies slowly relative to the tremor period — an "
        "approximation, not an exact recovery of the OU process."
    )
    lag1 = signal_summary.get("envelope_mean_lag1_autocorr")
    lines.append(f"- Mean lag-1 autocorrelation of the envelope proxy: "
                  f"{lag1:.3f}" if lag1 == lag1 else "- n/a")
    lines.append(
        "  (positive and well above 0 indicates smooth variation rather "
        "than independent white noise; no clinical claim is made about "
        "the OU parameters).\n"
    )

    lines.append("## 8. Clean-data preservation\n")
    lines.append(f"- Clean rows checked: {signal_summary.get('n_clean_rows', 'n/a')}")
    lines.append(f"- Violations (observed ≠ ground_truth): "
                  f"{signal_summary.get('clean_preservation_violations')}")
    lines.append(f"- Max error: {signal_summary.get('clean_preservation_max_error_px'):.6f} px")
    lines.append(f"- Result: {_pass_fail(clean_pass)}\n")

    lines.append("## 9. Event preservation\n")
    lines.append(f"- Violations on non-move rows in tremor trials: "
                  f"{signal_summary.get('event_preservation_violations')}")
    lines.append(f"- Max error: {signal_summary.get('event_preservation_max_error_px'):.6f} px")
    lines.append(f"- Result: {_pass_fail(event_pass)}\n")

    lines.append("## 10. Spatial validation (paired clean-vs-tremor)\n")
    if not spatial_df.empty:
        lines.append(f"- Tremor trials with spatial features computed: {len(spatial_df)}")
        lines.append(f"- Mean RMS deviation: {spatial_df['deviation_rms_px'].mean():.3f} px")
        lines.append(f"- Mean path-length increase: "
                      f"{spatial_df['path_length_change_percent'].mean():.2f}%")
        lines.append(f"- Mean direction-change increase: "
                      f"{spatial_df['direction_changes_increase'].mean():.2f}")
    else:
        lines.append("- No tremor trials available for spatial validation.")
    lines.append("- See `spatial_validation.csv`, `validation_plots/spatial_summary.png`.\n")

    lines.append("## 11. RobustPDX comparison\n")
    if robustpdx_available:
        lines.append(f"- RobustPDX traces loaded: {len(robustpdx_df)}")
        lines.append(
            "- RobustPDX was used as an external SPATIAL reference only — "
            "not as a temporal-frequency ground truth (its point sequences "
            "do not provide reliable per-point timestamps for 4/6/8/10 Hz "
            "validation)."
        )
        lines.append("- See `robustpdx_feature_summary.csv`, `robustpdx_comparison.csv`, "
                      "and `validation_plots/compare_*.png`.\n")
    else:
        lines.append(
            "- **Not run this session.** No RobustPDX file was configured/found. "
            "Pass `--robustpdx PATH` (and adjust `RobustPDXColumnMap` in "
            "`src/validation_robustpdx.py` to match its actual column names) "
            "to enable this comparison.\n"
        )

    lines.append("## 12. Statistical tests\n")
    if not comparison_df.empty and "ks_statistic" in comparison_df.columns:
        lines.append("KS statistic, KS p-value, Wasserstein distance, and Cohen's d were "
                      "computed for each shared feature against each RobustPDX group. "
                      "See `robustpdx_comparison.csv` for the full table. "
                      "**Statistical significance alone is not treated as evidence of "
                      "similarity** — distance measures and effect sizes are reported "
                      "together, per feature.\n")
    else:
        lines.append("Skipped — no RobustPDX reference data available this session.\n")

    lines.append("## 13. Limitations\n")
    lines.append(
        "- This report validates the IMPLEMENTED synthetic model against itself "
        "(did the code do what it was told to do) and, where RobustPDX is "
        "available, against external SPATIAL characteristics. It does **not** "
        "establish clinical validity.\n"
        "- The pixel amplitudes (2/4/6/8 px) are engineering simulation "
        "parameters, not physiological tremor amplitudes.\n"
        "- The 13 rad/s² value from Kulkarni et al. (2024) / Rocon et al. "
        "(2004) refers to wrist angular acceleration and is not directly "
        "equated with mouse-pixel displacement amplitude anywhere in this "
        "pipeline.\n"
        "- The stochastic envelope r(t) validation is an indirect "
        "(Hilbert-envelope) proxy, not an exact recovery of the underlying "
        "process.\n"
        "- RobustPDX, where used, is a spatial reference; its trace types "
        "(straight/sine/spiral tracing) are not claimed to correspond to "
        "this project's task labels (fast/normal/slow/drag/precision/...).\n"
    )

    lines.append("## 14. Conclusions\n")
    overall = freq_pass and clean_pass and event_pass and amp_pass
    lines.append(
        f"Overall generation-stage mathematical validation: {_pass_fail(overall)}. "
        "The synthetic-tremor trajectories exhibit spatial characteristics that "
        + ("are comparable to those observed in the available RobustPDX reference "
           "data for the evaluated features (see Section 11/12)."
           if robustpdx_available else
           "could not yet be compared to an external spatial reference "
           "(RobustPDX not configured this run).")
        + "\n"
    )

    lines.append("## 15. Recommended next steps\n")
    lines.append(
        "1. If any check above is FAIL, inspect `trial_level_validation.csv` "
        "for the specific offending trials before proceeding.\n"
        "2. If RobustPDX wasn't available this run, re-run "
        "`run_validation.py --robustpdx PATH` with the correct column mapping.\n"
        "3. Once this stage passes, move to windowing + feature extraction "
        "for Random Forest task/context classification (participant-level "
        "split already enforced upstream).\n"
        "4. After the RF stage, proceed to Adaptive Kalman Filter "
        "implementation and the Phase-4 stabilization validation "
        "(RMSE/MAE vs. ground truth, tremor-band PSD energy reduction, "
        "jitter, endpoint error) — kept separate from this stage "
        "intentionally.\n"
    )

    report_text = "\n".join(lines)
    report_path = outdir / "validation_report.md"
    report_path.write_text(report_text,encoding="utf-8")
    print(f"[validation_report] wrote {report_path}")
    return report_text
